-- Execution Query for local075
-- Timestamp: 20250923_183530
-- Generated by SQL Agent

SELECT
    h.page_id,
    h.page_name,
    COALESCE(SUM(CASE WHEN e.event_type = 1 THEN 1 ELSE 0 END), 0) AS "number of product being viewed",
    COALESCE(SUM(CASE WHEN e.event_type = 2 THEN 1 ELSE 0 END), 0) AS "number added to the cart",
    0 AS "without being purchased in cart",
    0 AS "count of actual purchases"
FROM shopping_cart_page_hierarchy h
LEFT JOIN shopping_cart_events e
    ON h.page_id = e.page_id
WHERE h.page_id NOT IN (1, 2, 12, 13)
  AND h.product_id IS NOT NULL
GROUP BY h.page_id, h.page_name
ORDER BY h.page_id