-- Execution Query for local244
-- Timestamp: 20250923_184231
-- Generated by SQL Agent

WITH track_durations AS (
  SELECT
    TrackId,
    Milliseconds,
    CAST(Milliseconds AS FLOAT) / 60000 AS duration_minutes,
    CASE
      WHEN (CAST(Milliseconds AS FLOAT) / 60000) < 3 THEN 'short'
      WHEN (CAST(Milliseconds AS FLOAT) / 60000) BETWEEN 3 AND 5 THEN 'medium'
      ELSE 'long'
    END AS LengthCateg
  FROM Track
),
track_revenue AS (
  SELECT
    TrackId,
    SUM(UnitPrice * Quantity) AS TotalPrice
  FROM InvoiceLine
  GROUP BY TrackId
)
SELECT
  MIN(td.duration_minutes) AS From_Minutes,
  MAX(td.duration_minutes) AS To_Minutes,
  td.LengthCateg,
  COALESCE(SUM(tr.TotalPrice), 0) AS TotalPrice
FROM track_durations td
LEFT JOIN track_revenue tr ON td.TrackId = tr.TrackId
GROUP BY td.LengthCateg
ORDER BY From_Minutes