-- Execution Query for local004
-- Timestamp: 20251019_213541
-- Generated by SQL Agent

WITH payments_per_order AS (
  -- Sum payment_value per order_id to handle multiple payment rows per order
  SELECT
    order_id,
    SUM(payment_value) AS total_payment
  FROM order_payments
  GROUP BY order_id
),
customer_orders AS (
  -- Join orders to customers and payments, get per-order payment and timestamp, and customer_unique_id
  SELECT
    c.customer_unique_id,
    o.order_id,
    o.order_purchase_timestamp,
    ppo.total_payment
  FROM orders o
  JOIN customers c ON o.customer_id = c.customer_id
  JOIN payments_per_order ppo ON o.order_id = ppo.order_id
),
customer_agg AS (
  -- Aggregate per customer: count orders, sum payments, min/max timestamp
  SELECT
    customer_unique_id,
    COUNT(DISTINCT order_id) AS PF,
    SUM(total_payment) * 1.0 / COUNT(DISTINCT order_id) AS AOV,
    MIN(order_purchase_timestamp) AS min_ts,
    MAX(order_purchase_timestamp) AS max_ts
  FROM customer_orders
  GROUP BY customer_unique_id
),
final AS (
  -- Compute ACL (customer lifespan in weeks), set to 1.0 if less than 1 week
  SELECT
    customer_unique_id,
    PF,
    AOV,
    CASE
      WHEN ((julianday(max_ts) - julianday(min_ts)) / 7.0) < 1.0 THEN 1.0
      ELSE ((julianday(max_ts) - julianday(min_ts)) / 7.0)
    END AS ACL
  FROM customer_agg
)
SELECT
  customer_unique_id,
  PF,
  AOV,
  ACL
FROM final
ORDER BY AOV DESC
LIMIT 3;