-- Execution Query for local037
-- Timestamp: 20250923_183033
-- Generated by SQL Agent

WITH category_payments AS (
    SELECT
        pr.product_category_name AS Category_name,
        p.payment_type,
        COUNT(*) AS payment_count
    FROM
        olist_order_items i
        JOIN olist_products pr ON i.product_id = pr.product_id
        JOIN olist_order_payments p ON i.order_id = p.order_id
    GROUP BY
        pr.product_category_name,
        p.payment_type
),
ranked_payments AS (
    SELECT
        Category_name,
        payment_type,
        payment_count,
        ROW_NUMBER() OVER (
            PARTITION BY Category_name
            ORDER BY payment_count DESC
        ) AS rn
    FROM
        category_payments
)
SELECT
    Category_name,
    payment_count
FROM
    ranked_payments
WHERE
    rn = 1
ORDER BY
    payment_count DESC
LIMIT 3;