-- Execution Query for local037
-- Timestamp: 20250922_105109
-- Generated by SQL Agent

WITH payment_category AS (
    SELECT DISTINCT
        p.order_id,
        p.payment_type,
        pr.product_category_name
    FROM olist_order_payments p
    JOIN olist_order_items i ON p.order_id = i.order_id
    JOIN olist_products pr ON i.product_id = pr.product_id
    WHERE pr.product_category_name IS NOT NULL
),
payment_counts AS (
    SELECT
        product_category_name,
        payment_type,
        COUNT(*) AS payment_count
    FROM payment_category
    GROUP BY product_category_name, payment_type
),
ranked_payments AS (
    SELECT
        product_category_name,
        payment_type,
        payment_count,
        ROW_NUMBER() OVER (
            PARTITION BY product_category_name
            ORDER BY payment_count DESC, payment_type
        ) AS rn
    FROM payment_counts
)
SELECT
    product_category_name AS Category_name,
    payment_count
FROM ranked_payments
WHERE rn = 1
ORDER BY payment_count DESC, Category_name
LIMIT 3;