-- Execution Query for local010
-- Timestamp: 20250923_182638
-- Generated by SQL Agent

WITH flight_cities AS (
  SELECT
    f.departure_airport,
    f.arrival_airport,
    dep.city AS dep_city_json,
    arr.city AS arr_city_json,
    dep.coordinates AS dep_coords,
    arr.coordinates AS arr_coords
  FROM flights f
  JOIN airports_data dep ON f.departure_airport = dep.airport_code
  JOIN airports_data arr ON f.arrival_airport = arr.airport_code
),
parsed_cities AS (
  SELECT
    SUBSTR(dep_city_json, INSTR(dep_city_json, '"en": "') + 7, INSTR(SUBSTR(dep_city_json, INSTR(dep_city_json, '"en": "') + 7), '"') - 1) AS dep_city_en,
    SUBSTR(arr_city_json, INSTR(arr_city_json, '"en": "') + 7, INSTR(SUBSTR(arr_city_json, INSTR(arr_city_json, '"en": "') + 7), '"') - 1) AS arr_city_en,
    CAST(SUBSTR(dep_coords, 2, INSTR(dep_coords, ',') - 2) AS REAL) AS dep_long,
    CAST(SUBSTR(dep_coords, INSTR(dep_coords, ',') + 1, LENGTH(dep_coords) - INSTR(dep_coords, ',') - 1) AS REAL) AS dep_lat,
    CAST(SUBSTR(arr_coords, 2, INSTR(arr_coords, ',') - 2) AS REAL) AS arr_long,
    CAST(SUBSTR(arr_coords, INSTR(arr_coords, ',') + 1, LENGTH(arr_coords) - INSTR(arr_coords, ',') - 1) AS REAL) AS arr_lat
  FROM flight_cities
),
city_pair_distances AS (
  SELECT
    CASE WHEN dep_city_en < arr_city_en THEN dep_city_en ELSE arr_city_en END AS city1,
    CASE WHEN dep_city_en < arr_city_en THEN arr_city_en ELSE dep_city_en END AS city2,
    6371 * 2 * 
      ASIN(
        SQRT(
          POWER(SIN(RADIANS((arr_lat - dep_lat) / 2)), 2) +
          COS(RADIANS(dep_lat)) * COS(RADIANS(arr_lat)) *
          POWER(SIN(RADIANS((arr_long - dep_long) / 2)), 2)
        )
      ) AS distance_km
  FROM parsed_cities
),
avg_pair_distances AS (
  SELECT city1, city2, AVG(distance_km) AS avg_distance
  FROM city_pair_distances
  GROUP BY city1, city2
),
binned_pairs AS (
  SELECT
    city1,
    city2,
    avg_distance,
    CASE
      WHEN avg_distance < 1000 THEN '0-999'
      WHEN avg_distance < 2000 THEN '1000-1999'
      WHEN avg_distance < 3000 THEN '2000-2999'
      WHEN avg_distance < 4000 THEN '3000-3999'
      WHEN avg_distance < 5000 THEN '4000-4999'
      WHEN avg_distance < 6000 THEN '5000-5999'
      ELSE '6000+'
    END AS distance_bin
  FROM avg_pair_distances
),
bin_counts AS (
  SELECT distance_bin, COUNT(*) AS pair_count
  FROM binned_pairs
  GROUP BY distance_bin
)
SELECT MIN(pair_count) AS output
FROM bin_counts;