-- Execution Query for local010
-- Timestamp: 20250922_103948
-- Generated by SQL Agent

WITH city_pair_distances AS (
  SELECT
    json_extract(dep.city, '$.en') AS dep_city_en,
    json_extract(arr.city, '$.en') AS arr_city_en,
    6371 * 2 * 
      ASIN(
        SQRT(
          POWER(SIN(RADIANS(
            CAST(SUBSTR(arr.coordinates, INSTR(arr.coordinates, ',')+1, LENGTH(arr.coordinates) - INSTR(arr.coordinates, ',') - 1) AS REAL) - 
            CAST(SUBSTR(dep.coordinates, INSTR(dep.coordinates, ',')+1, LENGTH(dep.coordinates) - INSTR(dep.coordinates, ',') - 1) AS REAL)
          ) / 2), 2) +
          COS(RADIANS(CAST(SUBSTR(dep.coordinates, INSTR(dep.coordinates, ',')+1, LENGTH(dep.coordinates) - INSTR(dep.coordinates, ',') - 1) AS REAL))) *
          COS(RADIANS(CAST(SUBSTR(arr.coordinates, INSTR(arr.coordinates, ',')+1, LENGTH(arr.coordinates) - INSTR(arr.coordinates, ',') - 1) AS REAL))) *
          POWER(SIN(RADIANS(
            CAST(SUBSTR(arr.coordinates, 2, INSTR(arr.coordinates, ',')-2) AS REAL) - 
            CAST(SUBSTR(dep.coordinates, 2, INSTR(dep.coordinates, ',')-2) AS REAL)
          ) / 2), 2)
        )
      ) AS distance_km
  FROM flights f
  JOIN airports_data dep ON f.departure_airport = dep.airport_code
  JOIN airports_data arr ON f.arrival_airport = arr.airport_code
)
, avg_pair_distances AS (
  SELECT
    dep_city_en,
    arr_city_en,
    AVG(distance_km) AS avg_distance
  FROM city_pair_distances
  WHERE dep_city_en <> arr_city_en
  GROUP BY dep_city_en, arr_city_en
)
, binned_pairs AS (
  SELECT
    CASE
      WHEN avg_distance < 1000 THEN '0'
      WHEN avg_distance < 2000 THEN '1000'
      WHEN avg_distance < 3000 THEN '2000'
      WHEN avg_distance < 4000 THEN '3000'
      WHEN avg_distance < 5000 THEN '4000'
      WHEN avg_distance < 6000 THEN '5000'
      ELSE '6000+'
    END AS distance_bin
  FROM avg_pair_distances
)
SELECT COUNT(*) AS output
FROM binned_pairs
GROUP BY distance_bin
ORDER BY COUNT(*) ASC
LIMIT 1;