-- Execution Query for local020
-- Timestamp: 20251019_214401
-- Generated by SQL Agent

WITH
-- Sum runs conceded per bowler (batsman runs + extra runs)
bowler_runs AS (
  SELECT
    b.bowler,
    SUM(COALESCE(bs.runs_scored, 0) + COALESCE(er.extra_runs, 0)) AS total_runs
  FROM
    ball_by_ball b
    LEFT JOIN batsman_scored bs
      ON b.match_id = bs.match_id AND b.over_id = bs.over_id AND b.ball_id = bs.ball_id
    LEFT JOIN extra_runs er
      ON b.match_id = er.match_id AND b.over_id = er.over_id AND b.ball_id = er.ball_id
  GROUP BY
    b.bowler
),
-- Count wickets taken per bowler
bowler_wickets AS (
  SELECT
    b.bowler,
    COUNT(*) AS wickets
  FROM
    wicket_taken w
    INNER JOIN ball_by_ball b
      ON w.match_id = b.match_id AND w.over_id = b.over_id AND w.ball_id = b.ball_id
  GROUP BY
    b.bowler
),
-- Calculate bowling average for bowlers with at least one wicket
bowling_averages AS (
  SELECT
    br.bowler,
    br.total_runs * 1.0 / bw.wickets AS bowling_average
  FROM
    bowler_runs br
    INNER JOIN bowler_wickets bw ON br.bowler = bw.bowler
  WHERE
    bw.wickets > 0
)
SELECT
  p.player_name AS output
FROM
  bowling_averages ba
  INNER JOIN player p ON ba.bowler = p.player_id
ORDER BY
  ba.bowling_average ASC
LIMIT 1;