-- Execution Query for local064
-- Timestamp: 20250923_183415
-- Generated by SQL Agent

WITH month_end_balances AS (
  SELECT
    customer_id,
    SUBSTR(txn_date, 1, 7) AS month,
    SUM(
      CASE
        WHEN txn_type = 'deposit' THEN txn_amount
        WHEN txn_type = 'withdrawal' THEN -txn_amount
        ELSE 0
      END
    ) AS month_end_balance
  FROM customer_transactions
  WHERE txn_date LIKE '2020-%'
    AND txn_type IN ('deposit', 'withdrawal')
  GROUP BY customer_id, month
),
month_positive_counts AS (
  SELECT
    month,
    COUNT(*) AS positive_count
  FROM month_end_balances
  WHERE month_end_balance > 0
  GROUP BY month
),
extremes AS (
  SELECT
    MAX(positive_count) AS max_count,
    MIN(positive_count) AS min_count
  FROM month_positive_counts
),
max_month AS (
  SELECT month
  FROM month_positive_counts, extremes
  WHERE positive_count = extremes.max_count
  LIMIT 1
),
min_month AS (
  SELECT month
  FROM month_positive_counts, extremes
  WHERE positive_count = extremes.min_count
  LIMIT 1
),
avg_balances AS (
  SELECT
    month,
    AVG(month_end_balance) AS avg_balance
  FROM month_end_balances
  WHERE month IN (SELECT month FROM max_month UNION SELECT month FROM min_month)
  GROUP BY month
),
pivot AS (
  SELECT
    MAX(CASE WHEN month = (SELECT month FROM max_month) THEN avg_balance END) AS max_avg_balance,
    MAX(CASE WHEN month = (SELECT month FROM min_month) THEN avg_balance END) AS min_avg_balance
  FROM avg_balances
)
SELECT
  (max_avg_balance - min_avg_balance) AS balance_diff
FROM pivot;