-- Execution Query for local064
-- Timestamp: 20250922_105953
-- Generated by SQL Agent

WITH months AS (
    SELECT '2020-01' AS month
    UNION ALL
    SELECT strftime('%Y-%m', date(month || '-01', '+1 month'))
    FROM months
    WHERE month < '2020-12'
),
customers AS (
    SELECT DISTINCT customer_id FROM customer_transactions
),
customer_months AS (
    SELECT c.customer_id, m.month
    FROM customers c
    CROSS JOIN months m
),
month_end_balances AS (
    SELECT
        cm.customer_id,
        cm.month,
        COALESCE(SUM(
            CASE
                WHEN ct.txn_type = 'deposit' THEN ct.txn_amount
                WHEN ct.txn_type IN ('withdrawal', 'purchase') THEN -ct.txn_amount
                ELSE 0
            END
        ), 0) AS month_end_balance
    FROM customer_months cm
    LEFT JOIN customer_transactions ct
        ON cm.customer_id = ct.customer_id
        AND strftime('%Y-%m', ct.txn_date) = cm.month
    GROUP BY cm.customer_id, cm.month
),
month_positive_counts AS (
    SELECT
        month,
        COUNT(*) AS positive_count
    FROM month_end_balances
    WHERE month_end_balance > 0
    GROUP BY month
),
extremes AS (
    SELECT
        month,
        positive_count
    FROM month_positive_counts
    WHERE positive_count = (SELECT MAX(positive_count) FROM month_positive_counts)
       OR positive_count = (SELECT MIN(positive_count) FROM month_positive_counts)
),
avg_balances AS (
    SELECT
        e.month,
        AVG(mb.month_end_balance) AS avg_balance
    FROM extremes e
    JOIN month_end_balances mb ON e.month = mb.month
    GROUP BY e.month
),
final AS (
    SELECT
        (MAX(avg_balance) - MIN(avg_balance)) AS balance_diff
    FROM avg_balances
)
SELECT balance_diff FROM final;