-- Execution Query for local007
-- Timestamp: 20250923_182605
-- Generated by SQL Agent

SELECT 
  ROUND(AVG(
    ROUND(ABS((julianday(final_game) - julianday(debut)) / 365), 2) +
    ROUND(ABS(((julianday(final_game) - julianday(debut)) % 365) / 30.44), 2) / 12 +
    ROUND(ABS(((julianday(final_game) - julianday(debut)) % 365) % 30.44), 2) / 365
  ), 6) AS output
FROM player
WHERE debut IS NOT NULL AND final_game IS NOT NULL;