-- Execution Query for local015
-- Timestamp: 20250923_182809
-- Generated by SQL Agent

WITH helmet_status AS (
    SELECT
        c.case_id,
        c.motorcyclist_killed_count,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM parties p
                WHERE p.case_id = c.case_id
                  AND (
                    (p.party_safety_equipment_1 LIKE '%motorcycle helmet used%')
                    OR (p.party_safety_equipment_2 LIKE '%motorcycle helmet used%')
                  )
            )
            THEN 'helmet_used'
            ELSE 'helmet_not_used'
        END AS helmet_group
    FROM collisions c
    WHERE c.motorcycle_collision = 1
),
agg AS (
    SELECT
        helmet_group,
        COUNT(*) AS total_collisions,
        SUM(motorcyclist_killed_count) AS total_killed
    FROM helmet_status
    GROUP BY helmet_group
)
SELECT
    COALESCE(ROUND(100.0 * (SELECT total_killed FROM agg WHERE helmet_group = 'helmet_used') / NULLIF((SELECT total_collisions FROM agg WHERE helmet_group = 'helmet_used'), 0), 2), 0) AS percent_killed_helmet_used,
    COALESCE(ROUND(100.0 * (SELECT total_killed FROM agg WHERE helmet_group = 'helmet_not_used') / NULLIF((SELECT total_collisions FROM agg WHERE helmet_group = 'helmet_not_used'), 0), 2), 0) AS percent_killed_helmet_not_used
;