-- Execution Query for local264
-- Timestamp: 20250923_184315
-- Generated by SQL Agent

SELECT L1_model, cnt AS max_cnt
FROM (
  SELECT m.L1_model, COUNT(*) AS cnt
  FROM model_score ms
  JOIN model m
    ON ms.name = m.name
   AND ms.version = m.version
   AND ms.step = m.step
  GROUP BY m.L1_model
)
ORDER BY cnt DESC
LIMIT 1;