-- Execution Query for local264
-- Timestamp: 20250917_171756
-- Generated by SQL Agent

WITH best_trad AS (
  SELECT
    ms.name,
    ms.version,
    ms.step,
    ROW_NUMBER() OVER (
      PARTITION BY ms.name, ms.version, ms.step
      ORDER BY ms.test_score DESC, ms.model ASC
    ) AS rn
  FROM model_score AS ms
  WHERE ms.model <> 'Stack'
)
SELECT
  m.L1_model,
  COUNT(*) AS max_cnt
FROM best_trad AS bt
JOIN model AS m
  ON bt.name = m.name
  AND bt.version = m.version
WHERE bt.rn = 1
GROUP BY m.L1_model
ORDER BY max_cnt DESC, m.L1_model ASC
LIMIT 1;