-- Execution Query for local157
-- Timestamp: 20250923_183910
-- Generated by SQL Agent

WITH parsed AS (
  SELECT
    ticker,
    market_date,
    volume,
    CASE
      WHEN volume = '-' THEN 0
      WHEN volume LIKE '%K' THEN CAST(REPLACE(volume, 'K', '') AS FLOAT) * 1000
      WHEN volume LIKE '%M' THEN CAST(REPLACE(volume, 'M', '') AS FLOAT) * 1000000
      ELSE CAST(volume AS FLOAT)
    END AS parsed_volume
  FROM bitcoin_prices
  WHERE SUBSTR(market_date, 7, 4) = '2021'
    AND SUBSTR(market_date, 4, 2) = '08'
    AND CAST(SUBSTR(market_date, 1, 2) AS INTEGER) BETWEEN 1 AND 10
)
SELECT
  p1.ticker,
  p1.market_date,
  p1.volume,
  (
    SELECT p2.parsed_volume
    FROM parsed p2
    WHERE p2.ticker = p1.ticker
      AND p2.market_date < p1.market_date
      AND p2.parsed_volume > 0
    ORDER BY p2.market_date DESC
    LIMIT 1
  ) AS previous_volume,
  CASE
    WHEN (
      SELECT p2.parsed_volume
      FROM parsed p2
      WHERE p2.ticker = p1.ticker
        AND p2.market_date < p1.market_date
        AND p2.parsed_volume > 0
      ORDER BY p2.market_date DESC
      LIMIT 1
    ) > 0
    THEN ROUND(
      (p1.parsed_volume - (
        SELECT p2.parsed_volume
        FROM parsed p2
        WHERE p2.ticker = p1.ticker
          AND p2.market_date < p1.market_date
          AND p2.parsed_volume > 0
        ORDER BY p2.market_date DESC
        LIMIT 1
      )) * 100.0 / (
        SELECT p2.parsed_volume
        FROM parsed p2
        WHERE p2.ticker = p1.ticker
          AND p2.market_date < p1.market_date
          AND p2.parsed_volume > 0
        ORDER BY p2.market_date DESC
        LIMIT 1
      ), 2)
    ELSE NULL
  END AS daily_change
FROM parsed p1
ORDER BY p1.ticker, p1.market_date;