-- Execution Query for local157
-- Timestamp: 20250922_093042
-- Generated by SQL Agent

WITH parsed AS (
  SELECT
    ticker,
    market_date,
    volume,
    CAST(SUBSTR(market_date, 7, 4) || SUBSTR(market_date, 4, 2) || SUBSTR(market_date, 1, 2) AS INTEGER) AS parsed_date,
    CASE
      WHEN volume = '-' THEN 0.0
      WHEN volume LIKE '%K' THEN REPLACE(volume, 'K', '') * 1000.0
      WHEN volume LIKE '%M' THEN REPLACE(volume, 'M', '') * 1000000.0
      ELSE volume * 1.0
    END AS parsed_volume
  FROM bitcoin_prices
)
SELECT
  p1.ticker,
  p1.market_date,
  p1.volume,
  (
    SELECT p2.parsed_volume
    FROM parsed p2
    WHERE p2.ticker = p1.ticker
      AND p2.parsed_date < p1.parsed_date
      AND p2.parsed_volume > 0
    ORDER BY p2.parsed_date DESC
    LIMIT 1
  ) AS previous_volume,
  (
    CASE
      WHEN (
        SELECT p2.parsed_volume
        FROM parsed p2
        WHERE p2.ticker = p1.ticker
          AND p2.parsed_date < p1.parsed_date
          AND p2.parsed_volume > 0
        ORDER BY p2.parsed_date DESC
        LIMIT 1
      ) IS NULL THEN NULL
      ELSE ROUND(
        (p1.parsed_volume - (
          SELECT p2.parsed_volume
          FROM parsed p2
          WHERE p2.ticker = p1.ticker
            AND p2.parsed_date < p1.parsed_date
            AND p2.parsed_volume > 0
          ORDER BY p2.parsed_date DESC
          LIMIT 1
        )) * 100.0 / (
          SELECT p2.parsed_volume
          FROM parsed p2
          WHERE p2.ticker = p1.ticker
            AND p2.parsed_date < p1.parsed_date
            AND p2.parsed_volume > 0
          ORDER BY p2.parsed_date DESC
          LIMIT 1
        ), 2)
    END
  ) AS daily_change
FROM parsed p1
WHERE p1.parsed_date BETWEEN 20210801 AND 20210810
ORDER BY p1.ticker, p1.parsed_date;